def fizz_buzz(n):
    if ((n%3==0) & (n%5==0)):
        print("FizzBuzz")
    elif (n%3==0):
        print("Fizz")
    elif(n%5==0):
        print("Buzz")
    else:
        print(n)

n=int(input("Enter the Number="))
fizz_buzz(n)
